"""empty message

Revision ID: 21403f10da12
Revises: 21bebdf5ffea
Create Date: 2020-06-08 09:45:59.604644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21403f10da12'
down_revision = '21bebdf5ffea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_activated')
    # ### end Alembic commands ###
